export type Preset = { id: string; name: string; tag: string; brand: string; accent: string }
export const presets: Preset[] = [
  { id: 'esmeralda', name: 'Esmeralda Bistró', tag: 'Restaurante', brand: '#0e7a5a', accent: '#f2a33a' },
  { id: 'tomate', name: 'Trattoria Tomate', tag: 'Pizzería', brand: '#c8372d', accent: '#f2b441' },
  { id: 'moka', name: 'Café Moka', tag: 'Cafetería', brand: '#7a4e33', accent: '#d99a4e' },
  { id: 'nori', name: 'Sushi Nori', tag: 'Asiática', brand: '#24313d', accent: '#e4573d' },
  { id: 'brasa', name: 'Brasa y Fuego', tag: 'Parrilla', brand: '#d4501a', accent: '#f0b429' },
  { id: 'neon', name: 'Bar Neón', tag: 'Coctelería', brand: '#7c3aed', accent: '#16c7e0' },
  { id: 'fresa', name: 'Heladería Fresa', tag: 'Heladería', brand: '#e0457b', accent: '#3cc0a6' },
  { id: 'trigo', name: 'Panadería Trigo', tag: 'Panadería', brand: '#b7791f', accent: '#7a9e3a' },
  { id: 'oceano', name: 'Océano', tag: 'Marisquería', brand: '#0b6fb8', accent: '#f2a33a' },
  { id: 'fresco', name: 'Verde Fresco', tag: 'Saludable', brand: '#3f8f3a', accent: '#f08a24' },
  { id: 'chile', name: 'Taquería Chile', tag: 'Mexicana', brand: '#b3261e', accent: '#2f9e6e' },
  { id: 'lavanda', name: 'Pastelería Lavanda', tag: 'Pastelería', brand: '#8e6bbf', accent: '#f08fb2' },
  { id: 'medianoche', name: 'Medianoche', tag: 'Alta cocina', brand: '#2d3b55', accent: '#d9aa45' },
  { id: 'indigo', name: 'Índigo Express', tag: 'Comida rápida', brand: '#4a4fd8', accent: '#ffb020' },
  { id: 'ambar', name: 'Cervecería Ámbar', tag: 'Cervecería', brand: '#b86f0a', accent: '#3b7a9e' },
  { id: 'tropical', name: 'Jugos Tropical', tag: 'Jugos', brand: '#ee6a1c', accent: '#2fb344' },
  { id: 'sakura', name: 'Rosa Sakura', tag: 'Té y brunch', brand: '#cf4d79', accent: '#6b94a8' },
  { id: 'matcha', name: 'Té Matcha', tag: 'Casa de té', brand: '#5b7f3b', accent: '#c9a24a' },
  { id: 'turquesa', name: 'Turquesa Caribe', tag: 'Playa / Bar', brand: '#0e8c97', accent: '#ff7a59' },
  { id: 'vino', name: 'Bodega Vino', tag: 'Vinoteca', brand: '#7d1f3d', accent: '#d8a657' },
  { id: 'carbon', name: 'Carbón', tag: 'Minimal', brand: '#303733', accent: '#e8c547' },
  { id: 'mostaza', name: 'Deli Mostaza', tag: 'Sándwiches', brand: '#c58b0a', accent: '#d6452f' },
]
